version: '3.8'

services:
  client:
    build:
      context: client
      dockerfile: client.dockerfile
    ports:
      - "8000:8000"
    environment:
      SERVER_URL: "http://server:9000/greeting/"
    depends_on:
      - server
    networks:
      - network1
  server:
    build:
      context: server
      dockerfile: server.dockerfile
    environment:
      SERVER_PORT: 9000
    networks:
      - network1
networks:
  network1:
    driver: bridge